import { NextResponse } from 'next/server';

/**
 * GET /api/conti-demo
 * 나노바나나 예시 촬영콘티 — D:opt 표준 포맷 데모
 * 각 컷별 AI 이미지 생성 프롬프트(JSON)를 포함하여
 * Google Imagen / Midjourney / DALL-E 등에서 바로 레퍼런스 이미지 생성 가능
 */
export async function GET() {
  const nanoBananaConti = {
    projectTitle: '나노바나나 프리미엄 바나나칩',
    shootDate: '2026-04-15 (수) 09:00~18:00',
    location: 'D:opt 스튜디오 A',
    team: '기획: 김디옵 / 촬영: 이포토 / 스타일리스트: 박스타',

    information: {
      productName: '나노바나나 프리미엄 바나나칩',
      lineup: [
        '오리지널 바나나칩 100g',
        '허니버터 바나나칩 100g',
        '초코 바나나칩 100g',
        '시나몬 바나나칩 100g',
      ],
      ingredients: '유기농 바나나 98%, 코코넛 오일 2% (오리지널 기준)',
      features: '동결건조 공법으로 바삭한 식감 / 무설탕 무첨가물 / 유기농 인증 / 개별 포장으로 휴대 간편',
      notes: '알레르기 유발 성분: 해당사항 없음 / 유통기한: 제조일로부터 12개월',
    },

    shootGuide: {
      imageStandard: '이미지 전달 기준 4000px (세로 기준), RGB 모드, JPG + RAW 파일 모두 전달',
      propNotice: '소품은 사전에 D:opt 스튜디오에서 준비 — 추가 소품 요청 시 촬영 3일 전까지 전달',
      productQty: '제품 수량 각 맛별 5개씩 총 20개 준비 (개봉용 + 미개봉 포함)',
      mockupNotice: '패키지 목업 인쇄본 준비 — 실제 패키지와 동일 색감으로 출력',
    },

    cutList: {
      total: 18,
      styled: 10,
      gif: 3,
      nukki: 4,
      ai: 1,
      rows: [
        { no: 1, type: '연출', detail: '히어로 — 4종 풀세트 메인 이미지', qty: 1 },
        { no: 2, type: '연출', detail: '히어로 — 오리지널 단품 메인', qty: 1 },
        { no: 3, type: '연출', detail: '성분 강조 — 바나나 원물 + 제품', qty: 1 },
        { no: 4, type: '연출', detail: '식감 표현 — 바나나칩 단면 클로즈업', qty: 1 },
        { no: 5, type: '연출', detail: '라이프스타일 — 데스크 간식 연출', qty: 1 },
        { no: 6, type: '연출', detail: '라이프스타일 — 피크닉/아웃도어', qty: 1 },
        { no: 7, type: '연출', detail: '4종 비교 — 맛별 라인업 나열', qty: 1 },
        { no: 8, type: '연출', detail: '패키지 디테일 — 앞면/뒷면', qty: 1 },
        { no: 9, type: '연출', detail: '사이즈감 표현 — 손에 들고 있는 컷', qty: 1 },
        { no: 10, type: '연출', detail: '플레이팅 — 그릇에 담긴 바나나칩', qty: 1 },
        { no: 11, type: 'GIF', detail: '바나나칩 부서지는 식감 모션', qty: 1 },
        { no: 12, type: 'GIF', detail: '봉지 오픈 + 칩 쏟아지는 모션', qty: 1 },
        { no: 13, type: 'GIF', detail: '4종 컬러 전환 루프', qty: 1 },
        { no: 14, type: '누끼', detail: '오리지널 패키지 정면', qty: 1 },
        { no: 15, type: '누끼', detail: '허니버터 패키지 정면', qty: 1 },
        { no: 16, type: '누끼', detail: '초코 패키지 정면', qty: 1 },
        { no: 17, type: '누끼', detail: '시나몬 패키지 정면', qty: 1 },
        { no: 18, type: 'AI', detail: 'AI 합성 — 바나나 농장 배경 이미지', qty: 1 },
      ],
    },

    conceptSummary: {
      concept: '자연 그대로의 건강한 간식을 강조하는 내추럴 프리미엄 무드. 유기농 바나나의 신선함과 동결건조 바삭함을 시각적으로 표현. 밝고 따뜻한 톤으로 건강하고 맛있는 느낌을 전달하되, 프리미엄 식품 브랜드 감성 유지.',
      keywords: ['#내추럴프리미엄', '#유기농간식', '#바삭한식감', '#건강한일상', '#동결건조'],
      colors: [
        { name: 'Main', hex: '#F5D547' },
        { name: 'Sub', hex: '#F5E6D0' },
        { name: 'Accent', hex: '#8B6914' },
        { name: 'Background', hex: '#FFF9E8' },
      ],
      mood: '내추럴 프리미엄 — 따뜻하고 밝은 자연광 느낌',
    },

    propList: [
      { item: '린넨 테이블 매트 (베이지)', qty: '2장', note: '촬영팀 보유' },
      { item: '우드 커팅보드', qty: '1개', note: '라운드형, 오크 소재' },
      { item: '화이트 세라믹 볼', qty: '3개', note: '미니 사이즈' },
      { item: '유기농 바나나 원물', qty: '10개', note: '촬영 당일 구매' },
      { item: '유칼립투스 잎', qty: '3줄기', note: '초록색 포인트용' },
      { item: '라탄 바구니', qty: '1개', note: '미디엄 사이즈' },
      { item: '피크닉 매트 (체크)', qty: '1장', note: '옐로우/화이트 체크' },
      { item: '텀블러 (화이트)', qty: '1개', note: '라이프스타일 소품' },
      { item: '크래프트 종이백', qty: '2장', note: '자연스러운 배경용' },
      { item: '손 모델용 네일 (내추럴톤)', qty: '1세트', note: '사이즈감 컷용' },
    ],

    cutPages: [
      {
        cutNum: 1,
        conceptNum: 'CONCEPT 01',
        type: '연출',
        background: { color: '#FFF9E8', description: '밝은 크림 옐로우 배경 — 브랜드 메인 컬러 톤' },
        composition: '[구도] 탑뷰 45도 — 4종 패키지를 부채꼴로 배치, 중앙에 바나나 원물과 바나나칩 흩뿌린 연출. 좌측 상단에서 대각선 자연광.',
        props: ['린넨 매트', '우드 커팅보드', '바나나 원물 3개', '바나나칩 소량 흩뿌림'],
        moodLighting: '자연광 (창가) + 은은한 리플렉터. 따뜻하고 부드러운 그림자.',
        sectionMapping: '히어로 섹션 (메인 이미지)',
        referenceNote: '프리미엄 그래놀라/건과일 브랜드 히어로 참고 — 심플하면서 풍성한 느낌',
        note: '4종 패키지 색상 차이가 명확히 보이도록 배치',
        imagePrompt: {
          subject: 'Four premium banana chip packages arranged in a fan layout, each with different flavor colors (yellow/original, gold/honey-butter, brown/chocolate, warm-orange/cinnamon)',
          scene: 'Elegant flat-lay food photography, packages arranged on a natural linen table mat with a round oak cutting board',
          foreground: 'Fresh whole bananas (3), scattered banana chips around the packages, natural and abundant arrangement',
          background: 'Warm cream-yellow surface (#FFF9E8), soft and clean',
          lighting: 'Warm natural window light from upper-left diagonal, soft reflector fill, gentle warm shadows',
          camera: {
            angle: 'Top-down 45-degree overhead',
            lens: '50mm equivalent',
            dof: 'Medium depth of field, slight blur on edges',
          },
          style: 'Premium food product photography, editorial quality, clean and natural aesthetic',
          colorPalette: ['#F5D547', '#F5E6D0', '#8B6914', '#FFF9E8'],
          mood: 'Natural premium, warm, fresh, healthy, abundant',
          negativePrompt: 'text, watermark, logo, blurry, low quality, artificial, plastic, cluttered, dark, cold tone',
          aspectRatio: '4:3',
          quality: 'ultra-high detail, 8K, commercial product photography',
        },
      },
      {
        cutNum: 2,
        conceptNum: 'CONCEPT 02',
        type: '연출',
        background: { color: '#FFFFFF', description: '퓨어 화이트 배경' },
        composition: '[구도] 정면 — 오리지널 단품 중앙 배치, 패키지 우측으로 바나나칩이 쏟아지는 듯한 연출. 밝고 깔끔한 스튜디오 촬영.',
        props: ['오리지널 패키지 1개', '바나나칩 다량', '투명 아크릴판 (칩 고정용)'],
        moodLighting: '스튜디오 조명 — 소프트박스 2등. 그림자 최소화.',
        sectionMapping: '히어로 섹션 (서브 이미지)',
        referenceNote: '깔끔한 제품 중심 촬영 — 식품 상세페이지 메인 컷 스타일',
        note: '칩이 자연스럽게 떨어지는 듯한 배치가 핵심',
        imagePrompt: {
          subject: 'Single premium banana chip package (yellow/gold design) centered, with dried banana chips spilling naturally from the right side of the package',
          scene: 'Clean studio product photography, single hero product shot',
          foreground: 'Banana chips cascading out of the package in a natural flowing arrangement, crispy golden texture visible',
          background: 'Pure white (#FFFFFF), seamless studio backdrop',
          lighting: 'Dual softbox studio lighting, minimal shadows, bright and even illumination',
          camera: {
            angle: 'Straight-on front view, slightly below eye level',
            lens: '85mm equivalent',
            dof: 'Sharp focus on product, very slight blur on distant chips',
          },
          style: 'E-commerce hero product photography, clean and premium, bright white background',
          colorPalette: ['#F5D547', '#FFFFFF', '#D4A017', '#F5E6D0'],
          mood: 'Clean, premium, appetizing, professional',
          negativePrompt: 'text, watermark, messy, dark shadows, colored background, cluttered',
          aspectRatio: '1:1',
          quality: 'ultra-high detail, 8K, commercial product photography',
        },
      },
      {
        cutNum: 3,
        conceptNum: 'CONCEPT 03',
        type: '연출',
        background: { color: '#F5E6D0', description: '웜 베이지 배경 — 자연스러운 톤' },
        composition: '[구도] 45도 — 바나나 원물을 반으로 자른 단면과 제품을 나란히 배치. "원재료→제품" 스토리라인 강조.',
        props: ['바나나 원물 (반절단)', '오리지널 패키지', '바나나칩 소량', '우드 커팅보드'],
        moodLighting: '자연광 + 리플렉터. 바나나 단면의 질감이 살도록 측광 활용.',
        sectionMapping: '성분/원재료 섹션',
        referenceNote: '유기농 식품 브랜드의 원재료 강조 촬영 참고',
        note: '바나나 단면의 신선함이 핵심 — 촬영 직전 커팅',
        imagePrompt: {
          subject: 'Fresh banana cut in half showing creamy cross-section, placed next to a premium banana chip package, with a few banana chips scattered between them',
          scene: 'Ingredient storytelling shot — raw material to finished product narrative',
          foreground: 'Halved fresh banana with visible creamy texture, banana chip package, scattered chips on oak cutting board',
          background: 'Warm beige surface (#F5E6D0), natural linen texture',
          lighting: 'Natural side light with reflector fill, emphasizing the cross-section texture of the fresh banana',
          camera: {
            angle: '45-degree angle',
            lens: '60mm macro-capable',
            dof: 'Shallow depth of field, sharp focus on banana cross-section',
          },
          style: 'Organic food ingredient photography, farm-to-table aesthetic, natural and fresh',
          colorPalette: ['#F5E6D0', '#F5D547', '#FFFBE0', '#8B6914'],
          mood: 'Fresh, natural, organic, honest, wholesome',
          negativePrompt: 'text, watermark, browning banana, wilted, artificial, plastic, dark',
          aspectRatio: '4:3',
          quality: 'ultra-high detail, 8K, macro food photography',
        },
      },
      {
        cutNum: 4,
        conceptNum: 'CONCEPT 04',
        type: '연출',
        background: { color: '#F5D547', description: '비비드 옐로우 — 식감 강조용 강렬한 배경' },
        composition: '[구도] 매크로 클로즈업 — 바나나칩 단면 촬영. 동결건조 기공과 바삭한 텍스처가 보이도록 최대 확대.',
        props: ['바나나칩 5~6개 (단면이 보이도록 부순 것 포함)'],
        moodLighting: '스튜디오 스팟 조명 — 텍스처 강조를 위한 측면 조명.',
        sectionMapping: '제조공정/식감 섹션',
        referenceNote: '식품 텍스처 매크로 촬영 — 칩/크래커 류 참고',
        note: '바삭한 기공 구조가 선명하게 보여야 함',
        imagePrompt: {
          subject: 'Extreme close-up of freeze-dried banana chips, showing the porous crispy internal structure and texture in sharp detail',
          scene: 'Macro food texture photography, focus on the crunchy cross-section of broken banana chips',
          foreground: '5-6 banana chips, some broken to reveal internal freeze-dried porous structure, golden crispy edges',
          background: 'Vivid yellow (#F5D547), bold and energetic',
          lighting: 'Studio spot light from the side to emphasize surface texture, dramatic shadows highlighting every pore and crack',
          camera: {
            angle: 'Macro close-up, straight-on',
            lens: '100mm macro',
            dof: 'Very shallow, razor-sharp focus on chip cross-section',
          },
          style: 'Macro food texture photography, editorial snack advertising, dramatic and appetizing',
          colorPalette: ['#F5D547', '#D4A017', '#8B6914', '#FFF0B3'],
          mood: 'Crunchy, crispy, satisfying, bold, textural',
          negativePrompt: 'text, watermark, blurry, soft, mushy, wet, dark, cold',
          aspectRatio: '16:9',
          quality: 'ultra-high detail, 8K, macro photography, extreme sharpness',
        },
      },
      {
        cutNum: 5,
        conceptNum: 'CONCEPT 05',
        type: '연출',
        background: { color: '#F0EDE8', description: '뉴트럴 그레이시 베이지 — 오피스 무드' },
        composition: '[구도] 45도 — 노트북/키보드 옆에 바나나칩 봉지 오픈 상태로 배치. 데스크 위 간식 연출.',
        props: ['오리지널 패키지 (오픈)', '노트북 모형', '커피잔', '펜', '린넨 매트'],
        moodLighting: '자연광 — 창가 데스크 환경. 밝고 산뜻한 느낌.',
        sectionMapping: '라이프스타일 섹션 (데스크)',
        referenceNote: '오피스 간식/건강 스낵 라이프스타일 촬영 참고',
        note: '자연스러운 일상 스냅 느낌으로',
        imagePrompt: {
          subject: 'Opened banana chip package placed casually next to a laptop on a modern desk, lifestyle office snacking scene',
          scene: 'Office desk lifestyle photography, healthy snacking moment during work',
          foreground: 'Opened banana chip bag with chips visible, next to a MacBook laptop, white coffee cup, pen, on a beige linen desk mat',
          background: 'Neutral greige surface (#F0EDE8), clean modern desk environment',
          lighting: 'Natural window light from the side, bright and airy, soft natural shadows',
          camera: {
            angle: '45-degree angle, casual perspective',
            lens: '35mm wide',
            dof: 'Medium depth of field, slight background blur on laptop screen',
          },
          style: 'Lifestyle product photography, candid and natural, modern office aesthetic',
          colorPalette: ['#F0EDE8', '#F5D547', '#FFFFFF', '#C0B9AE'],
          mood: 'Casual, productive, healthy, everyday, relatable',
          negativePrompt: 'text on screen, watermark, posed, artificial, dark, cluttered desk, messy',
          aspectRatio: '3:2',
          quality: 'high detail, lifestyle editorial photography',
        },
      },
      {
        cutNum: 6,
        conceptNum: 'CONCEPT 06',
        type: '연출',
        background: { color: '#E8F5E9', description: '라이트 그린 — 아웃도어/자연 느낌' },
        composition: '[구도] 정면 살짝 위 — 피크닉 매트 위에 바나나칩 + 과일 + 음료가 함께 배치된 피크닉 세팅.',
        props: ['피크닉 매트', '라탄 바구니', '바나나칩 2종', '텀블러', '사과/딸기', '유칼립투스 잎'],
        moodLighting: '야외 자연광 (또는 스튜디오에서 야외 느낌 연출). 밝고 경쾌한 분위기.',
        sectionMapping: '라이프스타일 섹션 (아웃도어)',
        referenceNote: '피크닉 간식/아웃도어 라이프스타일 촬영 참고',
        note: '풍성하고 즐거운 분위기 — 색감 다양하게',
        imagePrompt: {
          subject: 'Picnic scene with banana chip packages, fresh fruits, and drinks arranged on a checkered picnic mat with a rattan basket',
          scene: 'Outdoor picnic lifestyle photography, joyful and abundant spread',
          foreground: 'Two banana chip packages, rattan basket, white tumbler, fresh apples and strawberries, eucalyptus leaves, all on a yellow-white checkered picnic mat',
          background: 'Light green grassy tone (#E8F5E9), natural outdoor feeling',
          lighting: 'Bright outdoor natural sunlight, cheerful and vibrant, soft dappled light',
          camera: {
            angle: 'Slightly elevated front view, looking down at the picnic spread',
            lens: '28mm wide angle',
            dof: 'Deep depth of field, everything in focus, slight edge vignette',
          },
          style: 'Outdoor lifestyle product photography, picnic editorial, bright and joyful',
          colorPalette: ['#E8F5E9', '#F5D547', '#FF6B6B', '#FFFFFF', '#8FBC8F'],
          mood: 'Joyful, abundant, outdoor, healthy, colorful, cheerful',
          negativePrompt: 'text, watermark, indoor, dark, rainy, cold, sparse, boring',
          aspectRatio: '4:3',
          quality: 'high detail, outdoor lifestyle editorial photography',
        },
      },
      {
        cutNum: 7,
        conceptNum: 'CONCEPT 07',
        type: '연출',
        background: { color: '#FFF9E8', description: '크림 옐로우 배경' },
        composition: '[구도] 탑뷰 — 4종 패키지를 2x2 그리드로 정렬. 각 패키지 앞에 해당 맛 바나나칩을 소량 배치.',
        props: ['4종 패키지', '각 맛별 바나나칩', '화이트 세라믹 볼 4개'],
        moodLighting: '스튜디오 소프트박스 — 균일한 조명으로 4종 색감 차이 명확히.',
        sectionMapping: '라인업/맛 비교 섹션',
        referenceNote: '식품 라인업 비교 촬영 — 통일된 레이아웃',
        note: '각 맛별 컬러가 명확하게 구분되어야 함',
        imagePrompt: {
          subject: 'Four banana chip packages arranged in a 2x2 grid layout, each with a small white ceramic bowl of their respective flavor chips in front',
          scene: 'Product lineup comparison photography, systematic and organized grid layout',
          foreground: 'Four packages (original/yellow, honey-butter/gold, chocolate/brown, cinnamon/warm-orange) with matching chip samples in white bowls',
          background: 'Cream yellow surface (#FFF9E8), clean and uniform',
          lighting: 'Even studio softbox lighting, no harsh shadows, uniform illumination across all four products',
          camera: {
            angle: 'Perfectly top-down overhead, symmetrical',
            lens: '50mm',
            dof: 'Deep depth of field, all products equally sharp',
          },
          style: 'Product lineup comparison photography, systematic, clean grid layout, catalog style',
          colorPalette: ['#FFF9E8', '#F5D547', '#D4A017', '#8B4513', '#CD853F'],
          mood: 'Organized, clear, comparative, systematic, premium',
          negativePrompt: 'text, watermark, asymmetric, messy, uneven lighting, different sizes, cluttered',
          aspectRatio: '1:1',
          quality: 'ultra-high detail, 8K, commercial catalog photography',
        },
      },
      {
        cutNum: 8,
        conceptNum: 'CONCEPT 08',
        type: '연출',
        background: { color: '#FFFFFF', description: '화이트 배경' },
        composition: '[구도] 정면 — 패키지 앞면 + 뒷면을 나란히 배치. 영양성분표, 원재료 표시가 읽히도록.',
        props: ['오리지널 패키지 2개 (앞/뒤)'],
        moodLighting: '스튜디오 조명 — 텍스트가 선명하게 읽히도록 균일 조명.',
        sectionMapping: '패키지 디테일/영양정보 섹션',
        referenceNote: '식품 패키지 정보 촬영 참고',
        note: '텍스트 가독성이 최우선',
        imagePrompt: {
          subject: 'Two banana chip packages side by side — front label and back nutrition/ingredients panel clearly visible',
          scene: 'Package detail documentation photography, information-focused',
          foreground: 'Front package showing brand design and product imagery, back package showing nutrition facts table and ingredient list, both perfectly upright',
          background: 'Pure white (#FFFFFF), seamless',
          lighting: 'Even flat studio lighting, zero glare on package surface, all text perfectly legible',
          camera: {
            angle: 'Straight-on front view, perfectly level',
            lens: '85mm',
            dof: 'Deep depth of field, both packages equally sharp',
          },
          style: 'Package documentation photography, informational, clear and professional',
          colorPalette: ['#FFFFFF', '#F5D547', '#333333'],
          mood: 'Informative, trustworthy, transparent, clean',
          negativePrompt: 'text overlay, watermark, glare, reflection, blurry text, tilted, shadowed text',
          aspectRatio: '16:9',
          quality: 'ultra-high detail, 8K, text must be readable',
        },
      },
      {
        cutNum: 9,
        conceptNum: 'CONCEPT 09',
        type: '연출',
        background: { color: '#F5E6D0', description: '웜 베이지' },
        composition: '[구도] 정면 — 손 모델이 오리지널 패키지를 한 손에 들고 있는 컷. 손 대비 제품 사이즈감 표현.',
        props: ['오리지널 패키지', '손 모델'],
        moodLighting: '자연광 — 밝고 깨끗한 톤.',
        sectionMapping: '사이즈/용량 섹션',
        referenceNote: '제품 사이즈감 표현 촬영 참고 — 손+제품',
        note: '내추럴톤 네일, 손이 깨끗하게',
        imagePrompt: {
          subject: 'A clean, elegant female hand holding a banana chip package, showing the product size relative to hand scale',
          scene: 'Product scale reference photography, hand model holding the package naturally',
          foreground: 'Female hand with natural-tone manicure gently holding the banana chip package, fingers visible for size comparison',
          background: 'Warm beige (#F5E6D0), soft and clean',
          lighting: 'Bright natural light, clean and even, minimal shadows on hand',
          camera: {
            angle: 'Front view, package facing camera',
            lens: '85mm portrait',
            dof: 'Medium depth of field, sharp focus on package and hand',
          },
          style: 'Product scale photography, hand model, clean and elegant',
          colorPalette: ['#F5E6D0', '#F5D547', '#FFE4C4', '#FFFFFF'],
          mood: 'Elegant, clean, informative, approachable',
          negativePrompt: 'text, watermark, dirty hands, chipped nails, dark skin tones, overly styled, jewelry',
          aspectRatio: '3:4',
          quality: 'high detail, commercial hand model photography',
        },
      },
      {
        cutNum: 10,
        conceptNum: 'CONCEPT 10',
        type: '연출',
        background: { color: '#FFF9E8', description: '크림 옐로우 배경' },
        composition: '[구도] 45도 — 화이트 세라믹 볼에 바나나칩을 풍성하게 담고, 옆에 바나나 원물 배치. 푸드 스타일링.',
        props: ['화이트 세라믹 볼', '바나나칩 다량', '바나나 원물', '린넨 냅킨', '우드 스푼'],
        moodLighting: '자연광 + 리플렉터. 따뜻하고 먹음직스러운 톤.',
        sectionMapping: '플레이팅/먹는 방법 섹션',
        referenceNote: '푸드 플레이팅 촬영 — 건과일/그래놀라 스타일',
        note: '풍성하고 먹음직스러운 느낌 — 볼에 넘칠 듯이',
        imagePrompt: {
          subject: 'White ceramic bowl overflowing with golden banana chips, with a whole banana and wooden spoon beside it on a linen napkin',
          scene: 'Food plating photography, abundant and appetizing serving suggestion',
          foreground: 'Overflowing white ceramic bowl filled with banana chips, wooden spoon, linen napkin, fresh banana for context',
          background: 'Cream yellow surface (#FFF9E8), warm and inviting',
          lighting: 'Warm natural light with reflector fill, golden hour tone, appetizing warm shadows',
          camera: {
            angle: '45-degree angle, food photography standard',
            lens: '60mm',
            dof: 'Shallow depth of field, sharp on bowl center, soft edges',
          },
          style: 'Food plating photography, editorial food styling, granola/dried-fruit aesthetic',
          colorPalette: ['#FFF9E8', '#F5D547', '#FFFFFF', '#8B6914', '#F5E6D0'],
          mood: 'Abundant, appetizing, warm, homemade, inviting',
          negativePrompt: 'text, watermark, empty bowl, sparse, cold, dark, unappetizing, artificial',
          aspectRatio: '4:5',
          quality: 'ultra-high detail, 8K, food photography, appetizing warm tones',
        },
      },
      {
        cutNum: 11,
        conceptNum: 'GIF 01',
        type: 'GIF',
        background: { color: '#F5D547', description: '비비드 옐로우 배경' },
        composition: '[구도] 정면 — 바나나칩을 위에서 떨어뜨려 부서지는 순간 캡처. 슬로우모션 루프.',
        props: ['바나나칩 다량', '투명 아크릴판 (낙하용)'],
        moodLighting: '스튜디오 고속 촬영 조명 — 순간 포착용 플래시.',
        sectionMapping: '식감 표현 GIF',
        referenceNote: '식품 크런치/바삭 GIF 레퍼런스',
        note: '120fps 이상 고속 촬영 — 편집 시 슬로우모션 처리',
        imagePrompt: {
          subject: 'Banana chip shattering mid-air upon impact, freeze-frame moment of crunch, fragments and crumbs flying',
          scene: 'High-speed food photography capturing the exact moment a banana chip breaks, showing crispy texture',
          foreground: 'One banana chip breaking into pieces with fragments suspended in air, crumbs flying outward',
          background: 'Vivid yellow (#F5D547), bold and energetic',
          lighting: 'High-speed flash, frozen motion, sharp and dramatic studio lighting',
          camera: {
            angle: 'Front view, high-speed freeze frame',
            lens: '100mm macro',
            dof: 'Sharp focus on breaking point, slight motion blur on flying fragments',
          },
          style: 'High-speed food photography, freeze-frame crunch moment, dynamic and dramatic',
          colorPalette: ['#F5D547', '#D4A017', '#FFF0B3', '#8B6914'],
          mood: 'Dynamic, crunchy, satisfying, energetic, impactful',
          negativePrompt: 'text, watermark, blurry, soft, static, boring, dark',
          aspectRatio: '1:1',
          quality: 'ultra-high detail, high-speed photography, frozen motion',
        },
      },
      {
        cutNum: 12,
        conceptNum: 'GIF 02',
        type: 'GIF',
        background: { color: '#FFFFFF', description: '화이트 배경' },
        composition: '[구도] 정면 — 봉지를 열고 바나나칩이 쏟아지는 모션. 상단→하단 자연스러운 흐름.',
        props: ['오리지널 패키지', '바나나칩 다량'],
        moodLighting: '스튜디오 균일 조명.',
        sectionMapping: '오프닝/언박싱 GIF',
        referenceNote: '식품 패키지 오픈 GIF 참고',
        note: '자연스러운 쏟아짐 — 속도 적절히 조절',
        imagePrompt: {
          subject: 'Banana chip package tilted open with chips pouring out and cascading downward in a flowing stream',
          scene: 'Package opening moment, chips flowing out naturally from top to bottom',
          foreground: 'Opened banana chip package at top, stream of golden chips pouring down in a natural cascade',
          background: 'Pure white (#FFFFFF), seamless studio',
          lighting: 'Even studio lighting, chips illuminated as they fall',
          camera: {
            angle: 'Straight-on front view, vertical composition',
            lens: '85mm',
            dof: 'Medium depth of field, some chips in soft focus for depth',
          },
          style: 'Product unboxing photography, flowing cascade composition, clean and dynamic',
          colorPalette: ['#FFFFFF', '#F5D547', '#D4A017'],
          mood: 'Exciting, abundant, fresh opening, satisfying reveal',
          negativePrompt: 'text, watermark, static, dark, messy, blurry',
          aspectRatio: '9:16',
          quality: 'high detail, high-speed photography, flowing motion',
        },
      },
      {
        cutNum: 13,
        conceptNum: 'GIF 03',
        type: 'GIF',
        background: { color: '#F0F0F0', description: '라이트 그레이 배경' },
        composition: '[구도] 탑뷰 — 4종 패키지가 순서대로 화면에 등장하는 모션. 컬러 전환 루프.',
        props: ['4종 패키지'],
        moodLighting: '스튜디오 균일 조명.',
        sectionMapping: '라인업 소개 GIF',
        referenceNote: '제품 라인업 전환 GIF 참고',
        note: '각 맛 등장 타이밍 0.8초 — 자연스러운 전환',
        imagePrompt: {
          subject: 'Single banana chip package centered (original yellow flavor), this is one frame of a 4-frame color-transition loop GIF',
          scene: 'Product lineup rotation, clean centered display for animated color transition',
          foreground: 'One banana chip package perfectly centered, consistent position and size for seamless GIF transition between 4 flavors',
          background: 'Light gray (#F0F0F0), neutral and consistent',
          lighting: 'Perfectly even studio lighting, no shadows, consistent across all frames',
          camera: {
            angle: 'Top-down overhead, perfectly centered',
            lens: '50mm',
            dof: 'Deep depth of field, everything sharp',
          },
          style: 'Product rotation GIF frame, perfectly consistent positioning for animation',
          colorPalette: ['#F0F0F0', '#F5D547', '#D4A017', '#8B4513', '#CD853F'],
          mood: 'Systematic, clean, rhythmic, engaging',
          negativePrompt: 'text, watermark, different angles, inconsistent lighting, shadows, tilted',
          aspectRatio: '1:1',
          quality: 'high detail, consistent frame for GIF animation',
        },
      },
    ],

    nukkiGuide: '배경: 퓨어 화이트 (#FFFFFF)\n앵글: 정면 (모든 패키지 동일 앵글)\n그림자: 소프트 드롭 쉐도우 포함 (자연스러운 바닥 그림자)\n여백: 패키지 상하좌우 최소 15% 여백 확보\n해상도: 4000px 이상 (세로 기준)\n파일: PNG (배경 투명) + JPG (화이트 배경) 모두 전달\n주의: 패키지 표면 반사 최소화, 텍스트 가독성 확보',

    shootNotice: '1. 제품 라벨이 정확하게 정면을 향하도록 세팅\n2. 바나나 원물은 촬영 당일 아침에 구매 (갈변 방지)\n3. 바나나칩 개봉 후 30분 이내 촬영 (습기 흡수 방지)\n4. GIF 촬영 시 고속 촬영 모드 확인 필수\n5. 4종 패키지 색상 차이가 모니터와 실물이 일치하는지 캘리브레이션 확인',
  };

  return NextResponse.json(nanoBananaConti);
}
